services:
#  cassandra:
#    image: 'cassandra:latest'
#    environment:
#      - 'CASSANDRA_DC=dc1'
#      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
#    ports:
#      - '9042'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=farmabook'
      - 'POSTGRES_PASSWORD=Ganeshcb17'
      - 'POSTGRES_USER=ganesh'
    ports:
      - "5432:5432"
